config/routes.rb
Rails.application.routes.draw do
  resources :goals
  get 'archives/index'
  resources :entries
  root to: "entries#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord

    validates :calories, :proteins, :carbs, :fats, :meal_type, presence: true
    validates_numericality_of :calories, :proteins, :carbs, :fats, :greater_than => -1

    def day
        self.created_at.strftime("%b %e, %Y")
    end
end

app/models/goal.rb
class Goal < ApplicationRecord
    def day
        self.created_at.strftime("%b %e, %Y")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
    @goals = Goal.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbs, :fats)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[ show edit update destroy ]

  # GET /goals or /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1 or /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goal_params
      params.require(:goal).permit(:calorie_goal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/archives/index.html.erb
<div class ="columns mt-6 is-centered">
    <div class ="column is-half">
        <% @entries.each do |day, entries| %>
            <h3 class = "is-size-4 has-text-weight-bold mb-4 mt-2 has-text-centered"> Entries for <%= day %> </h3> 
            <nav class="level is-mobile">
                <div class = "level-item has-text-centered">
                    <div>
                        <p class = "heading">Calories</p>  
                        <p class = "title"><%= entries.pluck(:calories).sum %></p>
                    </div>
                </div>
                <div class = "level-item has-text-centered">
                    <div>
                        <p class = "heading">Protein</p>
                        <p class = "title"><%= entries.pluck(:proteins).sum %></p>
                    </div>
                </div>
                <div class = "level-item has-text-centered">
                    <div>
                        <p class = "heading">Carbs</p>
                        <p class = "title"><%= entries.pluck(:carbs).sum %></p>
                    </div>
                </div>
                <div class = "level-item has-text-centered">
                    <div>
                        <p class = "heading">Fats</p>
                        <p class = "title"><%= entries.pluck(:fats).sum %></p>
                    </div>
                </div>
            </nav>
        <% entries.each do |entry| %>
            <%= link_to entry_path(entry) do %>
                <div class = "card">
                    <div class = "card-content">
                        <strong><%= entry.meal_type%></strong><br/>
                        <%= entry.calories%> Calories
                        <%= entry.proteins %>g Protein
                        <%= entry.carbs %>g Carbs
                        <%= entry.fats %>g Fats
                    </div>  
                </div>
            <%end%>
        <%end%>
    <%end%>

    </div>
  </div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carbs:</strong>
    <%= entry.carbs %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>

    <div class="message is-danger">
      <div class="message is-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

  <div class = "message-body">
      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>

  <div class = "field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class = "field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class = "field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class = "field">
    <%= form.label :carbs, class: "label" %>
    <%= form.number_field :carbs, class: "input" %>
  </div>

  <div class = "field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class ="actions">
    <%= form.submit class: "button is-success"%>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class = "columns is-centered mt-6">
  <div class = "column is-one-third">
    <h1 class = "is-size-2 has-text-weight-bold mb-3" >Editing Entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
Foodlog &ndash; <%= DateTime.now.to_formatted_s(:nice_date) %>
<%end%>

<% if @entries.empty? %>
  <h3 class = "is-size-4 has-text-weight-bold mb-4 mt-6 has-text-centered"> There are no entries for today, add one! </h3>
<% else %>
  <div class ="columns mt-6 is-centered">
    <% @entries.each do |entry| %>
      <div class = "column is-one-quarter">
          <div class = "card"> 
            <header class = "card-header">
              <p class = "card-header-title"> <%=entry.meal_type%> </p>
            </header>
            <div class = "card-content">
              <div class = "content">
                <p><span class = "has-text-weight-bold"> <%=entry.calories %></span> Calories </p>
                <p><span class = "has-text-weight-bold"> <%=entry.proteins %></span>g Protein </p>
                <p><span class = "has-text-weight-bold"> <%=entry.carbs %></span>g Carbs </p>
              <p><span class = "has-text-weight-bold"> <%=entry.fats %></span>g Fats </p>
              <p class = "italic"> Logged at: <%= time_ago_in_words(entry.created_at) %> ago </p>
              </div>
            </div>
            <div class = "card-footer">
              <%= link_to "View", entry, class: "card-footer-item" %>
              <%= link_to "Edit", edit_entry_path(entry), class: "card-footer-item" %>
              <p class = "card-footer-item"> <%= link_to "Delete", entry, method: :delete, data: { confirm: "Are you sure?" }%> </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
 <% end %>

<div class= "columns mt-6 is-centered">
  <%=link_to "Create Entry", new_entry_path, class: "button is-link is-outline is-center mx-2"%>
  <%=link_to "Create Goal", new_goal_path, class: "button is-link is-outline is-center mx-2"%>
</div>
    

app/views/entries/new.html.erb
<div class = "columns is-centered mt-6">
  <div class = "column is-one-third">
    <h1 class = "is-size-2 has-text-weight-bold mb-3" >New Entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<%= content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.to_formatted_s(:nice_date)%>
<%end%>

<div class ="columns mt-6 is-centered">
  <div class ="column is-one-third">
    <nav class = "panel is-link">
      <p class = "panel-heading"> 
        <%= @entry.meal_type %>
      </p>
        <div class = "panel-block">
          Calories: <%= @entry.calories %>
        </div>
        <div class = "panel-block">
          Protein: <%= @entry.proteins %>
        </div>
        <div class = "panel-block">
          Carbs: <%= @entry.carbs %>
        </div>
        <div class = "panel-block">
          Fats: <%= @entry.fats %>
        </div>
    </nav>
      <div class = "columns is-mobile">
        <div class ="column">
            <%= link_to "Edit", edit_entry_path(@entry), class: "button is-gray" %>
            <%= link_to "Delete", @entry, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-gray" %> 
        </div>
      </div>
    </div>
  </div>

app/views/goals/_form.html.erb
<%= form_with(model: goal) do |form| %>
  <% if goal.errors.any? %>
   <div class="message is-danger">
      <div class="message is-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class = "message-body">
      <ul>
        <% goal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">
    <%= form.label :calorie_goal, class: "label" %>
    <%= form.number_field :calorie_goal, class: "input" %>
  </div>

 <div class ="actions">
    <%= form.submit class: "button is-success"%>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div id="<%= dom_id goal %>">
  <p>
    <strong>Calorie goal:</strong>
    <%= goal.calorie_goal %>
    <%= goal.created_at %>
  </p>

</div>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render "form", goal: @goal %>

<br>

<div>
  <%= link_to "Show this goal", @goal %> |
  <%= link_to "Back to goals", goals_path %>
</div>

app/views/goals/index.html.erb
<% content_for :title do %>
Goals 
<%end%>

<div class ="columns mt-6 is-centered">
    <% @goals.each do |goal| %>
    <div class = "column is-one-quarter">
        <div class = "card"> 
          <header class = "card-header">
            <p class = "card-header-title"> Calorie Goal for <%= goal.created_at.to_formatted_s(:nice_date) %> </p>
          </header>
          <div class = "card-content">
            <div class = "content">
              <p><span class = "has-text-weight-bold"> <%=goal.calorie_goal %></span> Calories </p>
              <% if goal.goal_met == false %> 
                <p><span class = "has-text-weight-bold has-text-danger"> Goal Not Met </span></p>
              <% else %>
                <p><span class = "has-text-weight-bold has-text-primary"> Goal Was Met </span></p>
              <% end %>
            </div>
          </div>
          <div class = "card-footer">
            <%= link_to "Edit", edit_goal_path(goal), class: "card-footer-item" %>
            <p class = "card-footer-item"> <%= link_to "Delete", goal, method: :delete, data: { confirm: "Are you sure?" }%> </p>
          </div>
        </div>
      </div>
     <% end %>
    </div>

app/views/goals/new.html.erb
<div class = "columns is-centered mt-6">
  <div class = "column is-one-third">
    <h1 class = "is-size-2 has-text-weight-bold mb-3" >New Daily Goal</h1>
    <%= render "form", goal: @goal %>
  </div>
</div>
<div>

app/views/goals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @goal %>

<div>
  <%= link_to "Edit this goal", edit_goal_path(@goal) %> |
  <%= link_to "Back to goals", goals_path %>

  <%= button_to "Destroy this goal", @goal, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    	<%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render "shared/header" %>

    <%if notice.present?%>
      <div class ="notification is-link is-light"><%= notice %></div>
    <%end%>

    <%if alert.present?%>
      <div class ="notification is-danger is-light"><%= alert %></div>
    <%end%>

    <div class ="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-primary is-link">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <span class = "has textweight-bold ml-4 is-size-4">Foodlog</span>
          <%end%>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Entries", archives_index_path, class: "navbar-link" %>
            <%= link_to "Goals", goals_path, class: "navbar-link" %>
          </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title)%>
            <%= yield :title%>
        <% else %>
            Foodlog
        <%end%>
      </p>
    </div>
  </div>

</section>


  